/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hdt.project;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dkmth
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    private String sen="";
    private String rec="";
    private String text="";
    private String nameSen;
    private String nameRec;
    
    public Chat() {
        initComponents();
    }
    public Chat(String s)
    {
        initComponents();
        this.sen=s;
        this.rec="";
        this.text="";
        if(sen.equals("admin"))
        {
            nameSen="admin";
        }
        else
            try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/sms","root","");
                    String sql=" Select * from student_information";
                    Statement st=(Statement) conn.createStatement();
                    ResultSet rs=st.executeQuery(sql);

                    while(rs.next())
                    {
                        String idGet=rs.getString("id");
                        if(sen.equals(idGet))
                        {
                           this.nameSen=rs.getString("name");
                           break;
                        }
                    }

                    sql=" Select * from teacher_information";
                    st=(Statement) conn.createStatement();
                    rs=st.executeQuery(sql);

                    while(rs.next())
                    {
                        String idGet=rs.getString("id");
                        if(sen.equals(idGet))
                        {
                           this.nameSen=rs.getString("name");
                           break;
                        }
                    }
                    conn.close();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        message = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        receiver = new javax.swing.JTextField();
        find = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        send.setText("Gửi");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        jLabel1.setText("Id người nhận:");

        find.setText("Tìm kiếm");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(find)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(message, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        String idEdit=receiver.getText();
        boolean check=false;
        if(idEdit.equals("admin"))
        {
            nameRec="admin";
            check=true;
        }
        else
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/sms","root","");
                String sql=" Select * from student_information";
                Statement st=(Statement) conn.createStatement();
                ResultSet rs=st.executeQuery(sql);

                while(rs.next())
                {
                    String idGet=rs.getString("id");
                    if(idEdit.equals(idGet))
                    {
                       check=true;
                       nameRec=rs.getString("name");
                       break;
                    }
                }
                sql="Select * from teacher_information";
                rs=st.executeQuery(sql);
                while(rs.next())
                {
                    String idGet=rs.getString("id");
                    if(idEdit.equals(idGet))
                    {
                        check=true;
                        nameRec=rs.getString("name");
                        break;
                    }
                }
                conn.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        if(check)
        {
            rec=idEdit;
            //Show thong tin chat
            
            text=nameRec+"\n"+"\n";
            String sql="Select * from "+sen+"_"+rec+" ";
            JOptionPane.showMessageDialog(null,sql);
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                Statement st=(Statement) conn.createStatement();
                ResultSet rs=st.executeQuery(sql);
                while(rs.next())
                {
                    if(sen.equals(rs.getString("id1")))
                        text+=nameSen+": "+rs.getString("msg")+"\n";
                    else 
                        text+=nameRec+": "+rs.getString("msg")+"\n";
                }
            }
            catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
            sql="Select * from "+rec+"_"+sen+" ";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                Statement st=(Statement) conn.createStatement();
                ResultSet rs=st.executeQuery(sql);
                while(rs.next())
                {
                    if(sen.equals(rs.getString("id1")))
                        text+=nameSen+": "+rs.getString("msg")+"\n";
                    else 
                        text+=nameRec+": "+rs.getString("msg")+"\n";
                }
            }
            catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
            textArea.setText(text);
            //
        }
        else
        {
            rec="";
            nameRec="";
            JOptionPane.showMessageDialog(null,"Khong co ai voi id = "+idEdit+"!");
        }
    }//GEN-LAST:event_findActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String Update="";
        int check=0;
        //JOptionPane.showMessageDialog(null,rec);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
            DatabaseMetaData metadata = conn.getMetaData();
            ResultSet resultSet;
            resultSet = metadata.getTables(null, null, sen+"_"+rec, null);
            //resultSet.next();
            if(resultSet.next()){
                check=1;
            }
            resultSet = metadata.getTables(null, null, rec+"_"+sen, null);
            if(resultSet.next()){
                check=2;    
            }
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        //JOptionPane.showMessageDialog(null,check);
        
        if(check==0 && message.getText()!="")
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                //JOptionPane.showMessageDialog(null,s);
                //JOptionPane.showMessageDialog(null,Update);
                Update="CREATE TABLE "+ sen+"_"+rec+" (\n" +
                "id1 VARCHAR(100) default NULL,\n" +
                "id2 VARCHAR(100) default NULL,\n" +
                "msg text default NULL\n" +
                ");";
                PreparedStatement st=conn.prepareStatement(Update);
                //JOptionPane.showMessageDialog(null,Update);
                st.executeUpdate();
                //JOptionPane.showMessageDialog(null,Update);
                String sql=" Insert into "+sen+"_"+rec +" values(?,?,?);";
                st=conn.prepareStatement(sql);
                st.setString(1,sen);
                st.setString(2,rec);
                st.setString(3,message.getText());
                st.executeUpdate();
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        else if(message.getText()!="")
        {
            if(check==1)
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                    PreparedStatement st;
                    String sql=" Insert into "+sen+"_"+rec +" values(?,?,?)";
                    st=conn.prepareStatement(sql);
                    st.setString(1,sen);
                    st.setString(2,rec);
                    st.setString(3,message.getText());
                    st.executeUpdate();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            else if(check==2)
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                    PreparedStatement st;
                    String sql=" Insert into "+rec+"_"+sen +" values(?,?,?)";
                    st=conn.prepareStatement(sql);
                    st.setString(1,sen);
                    st.setString(2,rec);
                    st.setString(3,message.getText());
                    st.executeUpdate();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
        }
        text=nameRec+"\n"+"\n";
            String sql="Select * from "+sen+"_"+rec+" ";
            
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                Statement st=(Statement) conn.createStatement();
                ResultSet rs=st.executeQuery(sql);
                while(rs.next())
                {
                    if(sen.equals(rs.getString("id1")))
                        text+=nameSen+": "+rs.getString("msg")+"\n";
                    else 
                        text+=nameRec+": "+rs.getString("msg")+"\n";
                }
            }
            catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
            sql="Select * from "+rec+"_"+sen+" ";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/chat","root","");
                Statement st=(Statement) conn.createStatement();
                ResultSet rs=st.executeQuery(sql);
                while(rs.next())
                {
                    if(sen.equals(rs.getString("id1")))
                        text+=nameSen+": "+rs.getString("msg")+"\n";
                    else 
                        text+=nameRec+": "+rs.getString("msg")+"\n";
                }
            }
            catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
            textArea.setText(text);
            message.setText("");
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton find;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message;
    private javax.swing.JTextField receiver;
    private javax.swing.JButton send;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
